In [9]:
import torch


x = torch.arange(75).view(3, 5, 5)
x


tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24]],

        [[25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]],

        [[50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64],
         [65, 66, 67, 68, 69],
         [70, 71, 72, 73, 74]]])

In [10]:
torch.flip(x, [1])

tensor([[[20, 21, 22, 23, 24],
         [15, 16, 17, 18, 19],
         [10, 11, 12, 13, 14],
         [ 5,  6,  7,  8,  9],
         [ 0,  1,  2,  3,  4]],

        [[45, 46, 47, 48, 49],
         [40, 41, 42, 43, 44],
         [35, 36, 37, 38, 39],
         [30, 31, 32, 33, 34],
         [25, 26, 27, 28, 29]],

        [[70, 71, 72, 73, 74],
         [65, 66, 67, 68, 69],
         [60, 61, 62, 63, 64],
         [55, 56, 57, 58, 59],
         [50, 51, 52, 53, 54]]])

In [6]:
# Sort the tensor along the last dimension
sorted_tensor, sorted_indices = torch.sort(x, dim=-1)
print("Sorted Tensor:\n", sorted_tensor)
print("Indices of the sorted elements:\n", sorted_indices)

Sorted Tensor:
 tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])
Indices of the sorted elements:
 tensor([[[0, 1],
         [0, 1]],

        [[0, 1],
         [0, 1]]])


In [14]:
x = x.float()

In [23]:
singular_values = torch.linalg.svdvals(x)
print("Singular values of the tensor x:\n", singular_values)
print("Shape of singular_values:", singular_values.shape)

Singular values of the tensor x:
 tensor([[6.9909e+01, 3.5761e+00, 2.0292e-06, 9.1606e-08, 5.3282e-10],
        [1.8848e+02, 1.3264e+00, 4.7493e-06, 1.3992e-06, 4.1856e-07],
        [3.1209e+02, 8.0105e-01, 8.4015e-06, 2.6620e-06, 3.4426e-07]])
Shape of singular_values: torch.Size([3, 5])


In [ ]:
print("x:\n", x)
print("sorted_tensor:\n", sorted_tensor)
print("sorted_indices:\n", sorted_indices)

In [24]:
singular_values.shape

torch.Size([3, 5])

In [25]:
sv =singular_values
sqrd_sv = sv**2
normed_sqrd_sv = torch.flip(torch.sort(sqrd_sv / torch.sum(sqrd_sv, dim=-1, keepdim=True))[0], dims=(0,)) 

In [26]:
torch.sum(normed_sqrd_sv, dim = -1)

tensor([1., 1., 1.])